### ISSUE TITLE
feat: 프로젝트의 기반 코드를 개발한다

### ISSUE THREAD

**Issue by Starlight258** [dnd-side-project/dnd-10th-2-backend#1]
## As-is
- 새로운 프로젝트로, 현재는 기반 코드가 없다.

## To-be 
- 새로운 프로젝트를 위한 기반 코드를 구축한다.

### 기대 효과
- Spring Security => 보안 강화
- 전역 예외 처리 => 예외 상황 일관된 처리
- DDD => 도메인을 서비스별로 분리하여 객체 지향에 기반한 유연성, 확장성, 유지 보수의 편리함

### Todo 
- [x]  프로젝트 기본 설정 및 Spring Security 설정
- [x]  전역 예외 처리 구현
- [x]  DB 연결
- [x]  DDD 패턴을 기반으로 한 기본 CRUD 개발(간단하게)

### References (optional)
- [DDD 패턴 1](https://dev-coco.tistory.com/166)
- [DDD 패턴 2](https://dev-coco.tistory.com/166)
