### ISSUE TITLE
feat: github action을 활용하여 Release 자동화를 수행한다 

### ISSUE THREAD

**Issue by FacerAin** [dnd-side-project/dnd-10th-2-backend#11]
## As-is
- 개발자가 직접 Release Versioning 및 문서 작성을 수행해야 한다.

## To-be 
- Github Action을 통해 commit 기록을 바탕으로 Release 자동화를 수행한다.

### 기대 효과
- 유지 보수 용이 및 개발자 생산성 향상

### Todo 
- [ ] mathieudutour/github-tag-action 적용
- [ ] ncipollo/release-action@v1 적용
- [ ] Deploy workflow Image push에 versioning 정보 적용

### References (optional)
- https://www.sktenterprise.com/bizInsight/blogDetail/dev/4555
