### ISSUE TITLE
feat: ERD 작성 후 코드에 반영한다.

### ISSUE THREAD

**Issue by Starlight258** [dnd-side-project/dnd-10th-2-backend#13]
## As-is
- 프로젝트의 ERD가 작성되지 않아 데이터 모델간의 관계를 이해하기 어렵다.

## To-be 
- ERD를 통해 데이터 모델 간의 관계를 쉽게 이해할 수 있다. 

### 기대 효과
- 기능 향상 : 데이터 모델 간의 명확한 관계 정의를 통해 기능 개발의 정확성과 신속성이 향상된다.

### Todo 
- [x]  Job1: 데이터 모델 간의 관계를 분석한다. 
- [x]  Job2 : ERD 초안을 작성한다. @FacerAin @Starlight258 
- [x] Job3 : 팀 Wiki에 ERD 문서를 업데이트한다.
- [x]  Job4 : 새로운 ERD에 따라 데이터베이스 스키마를 수정하고 코드를 업데이트한다.

### References (optional)
- [ERD best practices](https://www.linkedin.com/advice/1/what-some-common-mistakes-best-practices)
