### ISSUE TITLE
feat: 회의 관리(생성, 조회, 종료, 삭제) api를 개발한다

### ISSUE THREAD

**Issue by Starlight258** [dnd-side-project/dnd-10th-2-backend#19]
## As-is
- 현재 시스템에서는 회의를 생성하고 종료하는 기능이 없습니다. 

## To-be 
-  회의 생성과 종료 기능 api를 제공합니다.

### Todo 
- [x]  회의 생성 API 개발 (링크 기능 제외)
- [x]  회의 참가 API 개발
- [ ]  링크 기능 포함한 회의 생성 API 개발
- [ ]  회의 조회 API 개발(회의 상태에 따른 조회 구현)
- [ ]  회의 종료 API 개발
- [ ]  회의 삭제 API 개발
- [ ]  API 테스트 및 문서 업데이트

### References (optional)
- [팀 API 문서](https://pewter-wall-e50.notion.site/API-0f333c38fbc241ecbe9a80a0847f3149?pvs=74)
