### ISSUE TITLE
feat: 웹소켓 요청시 인증 로직을 구현한다 

### ISSUE THREAD

**Issue by Starlight258** [dnd-side-project/dnd-10th-2-backend#37]
## As-is
- 현재 웹소켓으로 안건 제어 요청시 회의에 참여하지 않은 사람도 요청을 보낼 수 있다.

## To-be 
- 웹소켓 사용시 요청 보내는 사람을 인증하여 적절한 권한을 가진 사람만 요청을 보낼 수 있도록 한다.

### 기대 효과
- 인증 로직을 구현하여 신뢰성이 높아진다.

### Todo 
- [x]  Job1: 웹소켓 인증 처리 방법 조사
- [x]  Job2 : 인증 처리 코드 구현
- [x]  Job3 : API 문서에 반영

### References (optional)
- [sample](https://www.google.com/)
