### ISSUE TITLE
feat: 배포 전략 변경을 반영한다. (ecs -> docker compose)

### ISSUE THREAD

**Issue by FacerAin** [dnd-side-project/dnd-10th-2-backend#38]
## As-is
- ECR-ECS 기반 배포 전략을 사용하고 있었음.

## To-be 
- AWS 크레딧 제한으로 인한 로컬 홈서버 (도커 기반)으로 배포 전략 변경 필요

### 기대 효과
- 배포 비용 절감

### Todo 
- [ ]  Docker deploy 환경 세팅
- [ ]  Github Action 반영
- [ ]  인스턴스 관리를 위한 게스트 계정 추가
