### ISSUE TITLE
feat: Production 용 Mysql 연결을 추가한다.

### ISSUE THREAD

**Issue by FacerAin** [dnd-side-project/dnd-10th-2-backend#42]
## As-is
-  테스트 및 디버깅 용으로 h2 DB만 사용하고 있음.

## To-be 
- 안정적인 배포 운용을 위한 mysql db가 필요함

### 기대 효과
- mysql db를 활용한 안정적인 배포 환경 운용

### Todo 
- [ ]  mysql 관련 config 파일 세팅
- [ ]  docker compose를 통한 mysql 컨테이너 추가
- [ ]  정상 동작 테스트
