### ISSUE TITLE
feat: 프로젝트를 도커라이징한다

### ISSUE THREAD

**Issue by FacerAin** [dnd-side-project/dnd-10th-2-backend#5]
## As-is
- 현재 별도의 컨테이너, 가상화 기술이 적용되어 있지 않음.

## To-be 
- Docker를 통하여 프로젝트의 컨테이너 가상화

### 기대 효과
- Docker를 통한 컨테이너 가상화 기술의 이점: 배포 및 관리의 편의성

### Todo 
- [x]  Dockerfile 만들기 @Starlight258 
- [x]  Docker-compose를 통한 DB-Spring 컨테이너 연결
- [x]  Image 레지스트리 선정하기 (Dockerhub VS ECS)
- [x] Github Action을 활용한 도커 build 및 push 파이프라인 작성하기 @FacerAin 

### References (optional)
- [docker 및 docker-compose 활용 스프링 프로젝트](https://github.com/KHUMON-EDU/back-end/)
