### ISSUE TITLE
feat: 회의 종료시 회의 및 안건 상태 관리와 권한 확인을 수행한다.

### ISSUE THREAD

**Issue by Starlight258** [dnd-side-project/dnd-10th-2-backend#51]
## As-is
- 회의 종료시 진행중인 안건이나 시작되지 않은 안건들에 대한 상태 관리가 되지 않는다.
- 회의 종료를 모든 사람이 요청할 수 있다.
- 회의 종료 버튼을 누르지 않으면 회의가 계속 INPROGRESS 상태이다.

## To-be 
- 회의가 종료되면 진행중인 안건은 종료되고 시작되지 않은 안건들은 취소된다.
- 회의 종료는 방장만 요청할 수 있다.
- 회의 종료 버튼을 누르지 않아도 회의 남은 시간이 끝나면 종료된다.

### 기대 효과
- 회의와 회의에 속해있는 안건들의 상태가 일관성있게 보장된다.
- 방장과 회의 참가자의 권한을 명확하게 분리한다.

### Todo 
- [x]  Job1: 회의 종료시 관련 안건 상태 관리 기능 구현
- [x] Job2 : 방장만 회의 종료할 수 있도록 수정
- [x] Job3: 스케줄러를 이용해 회의 남은시간이 끝나면 종료되도록 구현
